// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Entity
{
    public class DatosMultiplay
    {
        public int Id { get; set; }
        public int SubRegistro { get; set; }
        public string RegBaGen { get; set; }
        public int Cuenta  { get; set; }
        public decimal? Custcode  { get; set; }
        public string TipoCuscode { get; set; }
        public int Min { get; set; }
        public int CustomerId { get; set; }
        public string NombreCliente { get; set; }
        public int Cedula { get; set; }
        public int EstratoCliente { get; set; }
        public string EstadoAC { get; set; }
        public string EstadoRR { get; set; }
        public int SaldoActualAC { get; set; }
        public int SaldoEquipoAC { get; set; }
        public int SaldoEquipoAscard { get; set; }
        public int SaldoGrupo1 { get; set; }
        public int SaldoGrupo2 { get; set; }
        public int SaldoGrupo3 { get; set; }
        public int SaldoTotalRR { get; set; }
        public string EscVentaCliente { get; set; }
        public string AplicAjusteRR { get; set; }
        public string CampañaCaida { get; set; }
        public int ValoraAjustarInternet { get; set; }
        public int ValoraAjustarTv { get; set; }
        public int ValoraAjustarTel { get; set; }
        public int ValAjuOtrosConcep { get; set; }
        public int ValTotAjuFijo { get; set; }
        public string PerCamNoApliRR { get; set; }
        public string ObservacionesAjustes { get; set; }
        public string AjusteAC { get; set; }
        public string CamOfComApliCliente { get; set; }
        public string CamAplACDiVenta { get; set; }
        public int CfmDatosAntesIva { get; set; }
        public int CfmDatosAntesIva4Ipoc { get; set; }
        public int CfmVozAntesIva4Ipoc { get; set; }
        public string FechaACTMultAC { get; set; }
        public string TiempoCampañaCFMAAjustar { get; set; }
        public string PagosACNoRefleRR { get; set; }
        public string FechaPago1 { get; set; }
        public int ValorPago1 { get; set; }
        public string PagosRRNoRefleAC { get; set; }
        public string FechaPago2 { get; set; }
        public int ValorPago2 { get; set; }
        public string PagoCambiarGrupo { get; set; }
        public string Fecha1 { get; set; }
        public int Valor1 { get; set; }
        public string GrupoActual { get; set; }
        public string GrupoDebeQuedar { get; set; }
        public string PagAnuACNoApliACy_0RR { get; set; }
        public int Valor2 { get; set; }
        public string FechaIngresoPago { get; set; }
        public string PlataformaRepPagoAnulado { get; set; }
        public string AnularPago { get; set; }
        public string Fecha2{ get; set; }
        public int Valor3 { get; set; }
        public string Plataforma { get; set; }
        public string ArrPropClieRR { get; set; }
        public string NotasAdicionales { get; set; }
        public string Escenario1 { get; set; }
        public string AgenteGestiona { get; set; }
        public System.DateTime? FechaGestion { get; set; }
    }
}
