// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Entity
{

    // TBL_LINEA
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class Linea
    {
        public int Id { get; set; } // ID (Primary key)
        public string Nombre { get; set; } // NOMBRE (length: 20)
        public int? IdModoLogin { get; set; } // ID_MODO_LOGIN

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Acceso> Accesoes { get; set; } // TBL_ACCESOS.FK__TBL_ACCES__ID_LI__07C12930

        // Foreign keys
        public virtual ModosLogin ModosLogin { get; set; } // FK__TBL_LINEA__ID_MO__04E4BC85

        public Linea()
        {
            Accesoes = new System.Collections.Generic.List<Acceso>();
        }
    }

}
// </auto-generated>
