// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Entity
{

    // TBL_LOG_CIERRE_CICLO
    public class LogCierreCiclo
    {
        public int Id { get; set; } // ID
        public System.DateTime? FechaGestion { get; set; } // FECHA_GESTION
        public string UsuarioGestion { get; set; } // USUARIO_GESTION (length: 50)
        public string AliadoGestion { get; set; } // ALIADO_GESTION (length: 50)
        public double? Cuenta { get; set; } // CUENTA
        public decimal? Ofrecimiento1 { get; set; } // OFRECIMIENTO_1
        public decimal? Ofrecimiento2 { get; set; } // OFRECIMIENTO_2
        public decimal? Ofrecimiento3 { get; set; } // OFRECIMIENTO_3
        public decimal? PServicio1 { get; set; } // P_SERVICIO_1
        public decimal? PServicio2 { get; set; } // P_SERVICIO_2
        public decimal? PServicio3 { get; set; } // P_SERVICIO_3
        public decimal? PServicio4 { get; set; } // P_SERVICIO_4
        public decimal? PServicio5 { get; set; } // P_SERVICIO_5
        public decimal? PServicio6 { get; set; } // P_SERVICIO_6
        public decimal? PServicio7 { get; set; } // P_SERVICIO_7
        public decimal? PServicio8 { get; set; } // P_SERVICIO_8
        public decimal? PServicio9 { get; set; } // P_SERVICIO_9
        public decimal? PServicio10 { get; set; } // P_SERVICIO_10
        public decimal? PServicio11 { get; set; } // P_SERVICIO_11
        public decimal? PServicio12 { get; set; } // P_SERVICIO_12
        public decimal? PServicio13 { get; set; } // P_SERVICIO_13
        public decimal? PServicio14 { get; set; } // P_SERVICIO_14
        public decimal? PServicio15 { get; set; } // P_SERVICIO_15
        public decimal? PServicio16 { get; set; } // P_SERVICIO_16
        public decimal? PServicio17 { get; set; } // P_SERVICIO_17
        public decimal? PServicio18 { get; set; } // P_SERVICIO_18
        public decimal? PServicio19 { get; set; } // P_SERVICIO_19
        public decimal? PServicio20 { get; set; } // P_SERVICIO_20
        public decimal? PServicio21 { get; set; } // P_SERVICIO_21
        public decimal? PServicio22 { get; set; } // P_SERVICIO_22
        public decimal? PServicio23 { get; set; } // P_SERVICIO_23
        public decimal? PServicio24 { get; set; } // P_SERVICIO_24
        public decimal? PServicio25 { get; set; } // P_SERVICIO_25
        public decimal? PServicio26 { get; set; } // P_SERVICIO_26
        public decimal? PServicio27 { get; set; } // P_SERVICIO_27
        public decimal? PServicio28 { get; set; } // P_SERVICIO_28
        public decimal? PServicio29 { get; set; } // P_SERVICIO_29
        public decimal? PServicio30 { get; set; } // P_SERVICIO_30
        public decimal? PServicio31 { get; set; } // P_SERVICIO_31
        public decimal? PServicio32 { get; set; } // P_SERVICIO_32
        public decimal? PServicio33 { get; set; } // P_SERVICIO_33
        public decimal? PServicio34 { get; set; } // P_SERVICIO_34
        public decimal? PServicio35 { get; set; } // P_SERVICIO_35
        public decimal? PServicio36 { get; set; } // P_SERVICIO_36
        public string TipoContacto { get; set; } // TIPO_CONTACTO (length: 50)
        public string Gestion { get; set; } // GESTION (length: 100)
        public string Cierre { get; set; } // CIERRE (length: 100)
        public string Razon { get; set; } // RAZON (length: 100)
        public string Obervaciones { get; set; } // OBERVACIONES (length: 1000)
        public string Base { get; set; } // BASE (length: 50)
        public string OperacionGestion { get; set; } // OPERACION_GESTION (length: 50)
        public string Motivo { get; set; } // MOTIVO (length: 100)
        public string Seguimiento { get; set; } // SEGUIMIENTO (length: 2)
        public System.DateTime? FechaSeguimiento { get; set; } // FECHA_SEGUIMIENTO
    }

}
// </auto-generated>
