// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;

namespace Telmexla.Servicios.DIME.Entity
{

    // TBL_LOG_CIERRE_CICLO
    public class LogCierreCiclo
    {
        public int Id { get; set; } // ID
        public System.DateTime? FechaGestion { get; set; } // FECHA_GESTION
        public string UsuarioGestion { get; set; } // USUARIO_GESTION (length: 50)
        public string AliadoGestion { get; set; } // ALIADO_GESTION (length: 50)
        public double? Cuenta { get; set; } // CUENTA
        public decimal? Ofrecimiento1 { get; set; } // OFRECIMIENTO_1
        public decimal? Ofrecimiento2 { get; set; } // OFRECIMIENTO_2
        public decimal? Ofrecimiento3 { get; set; } // OFRECIMIENTO_3
        public decimal? PServicio1 { get; set; } // P_SERVICIO_1
        public decimal? PServicio2 { get; set; } // P_SERVICIO_2
        public decimal? PServicio3 { get; set; } // P_SERVICIO_3
        public decimal? PServicio4 { get; set; } // P_SERVICIO_4
        public decimal? PServicio5 { get; set; } // P_SERVICIO_5
        public decimal? PServicio6 { get; set; } // P_SERVICIO_6
        public decimal? PServicio7 { get; set; } // P_SERVICIO_7
        public decimal? PServicio8 { get; set; } // P_SERVICIO_8
        public decimal? PServicio9 { get; set; } // P_SERVICIO_9
        public decimal? PServicio10 { get; set; } // P_SERVICIO_10
        public decimal? PServicio11 { get; set; } // P_SERVICIO_11
        public decimal? PServicio12 { get; set; } // P_SERVICIO_12
        public decimal? PServicio13 { get; set; } // P_SERVICIO_13
        public decimal? PServicio14 { get; set; } // P_SERVICIO_14
        public decimal? PServicio15 { get; set; } // P_SERVICIO_15
        public decimal? PServicio16 { get; set; } // P_SERVICIO_16
        public decimal? PServicio17 { get; set; } // P_SERVICIO_17
        public decimal? PServicio18 { get; set; } // P_SERVICIO_18
        public decimal? PServicio19 { get; set; } // P_SERVICIO_19
        public decimal? PServicio20 { get; set; } // P_SERVICIO_20
        public decimal? PServicio21 { get; set; } // P_SERVICIO_21
        public decimal? PServicio22 { get; set; } // P_SERVICIO_22
        public decimal? PServicio23 { get; set; } // P_SERVICIO_23
        public decimal? PServicio24 { get; set; } // P_SERVICIO_24
        public decimal? PServicio25 { get; set; } // P_SERVICIO_25
        public decimal? PServicio26 { get; set; } // P_SERVICIO_26
        public decimal? PServicio27 { get; set; } // P_SERVICIO_27
        public decimal? PServicio28 { get; set; } // P_SERVICIO_28
        public decimal? PServicio29 { get; set; } // P_SERVICIO_29
        public decimal? PServicio30 { get; set; } // P_SERVICIO_30
        public decimal? PServicio31 { get; set; } // P_SERVICIO_31
        public decimal? PServicio32 { get; set; } // P_SERVICIO_32
        public decimal? PServicio33 { get; set; } // P_SERVICIO_33
        public decimal? PServicio34 { get; set; } // P_SERVICIO_34
        public decimal? PServicio35 { get; set; } // P_SERVICIO_35
        public decimal? PServicio36 { get; set; } // P_SERVICIO_36
        public string TipoContacto { get; set; } // TIPO_CONTACTO (length: 50)
        public string Gestion { get; set; } // GESTION (length: 100)
        public string Cierre { get; set; } // CIERRE (length: 100)
        public string Razon { get; set; } // RAZON (length: 100)
        public string Obervaciones { get; set; } // OBERVACIONES (length: 1000)
        public string Base { get; set; } // BASE (length: 50)
        public string OperacionGestion { get; set; } // OPERACION_GESTION (length: 50)
        public string Motivo { get; set; } // MOTIVO (length: 100)
        public string Seguimiento { get; set; } // SEGUIMIENTO (length: 2)
        public System.DateTime? FechaSeguimiento { get; set; } // FECHA_SEGUIMIENTO

        public static explicit operator LogCierreCiclo(CierreCiclo v)
        {
            LogCierreCiclo logCierreCiclo = new LogCierreCiclo();
            logCierreCiclo.AliadoGestion = v.AliadoGestion;
            logCierreCiclo.Base = v.Base;
            logCierreCiclo.Cierre = v.Cierre;
            logCierreCiclo.Cuenta = v.Cuenta;
            logCierreCiclo.FechaGestion = v.FechaGestion;
            logCierreCiclo.FechaSeguimiento = v.FechaSeguimiento;
            logCierreCiclo.Gestion = v.Gestion;
            logCierreCiclo.Motivo = v.Motivo;
            logCierreCiclo.Obervaciones = v.Obervaciones;
            logCierreCiclo.Ofrecimiento1 = v.Ofrecimiento1;
            logCierreCiclo.Ofrecimiento2 = v.Ofrecimiento2;
            logCierreCiclo.Ofrecimiento3 = v.Ofrecimiento3;
            logCierreCiclo.OperacionGestion = v.OperacionGestion;
            logCierreCiclo.PServicio1 = v.PServicio1;
            logCierreCiclo.PServicio10 = v.PServicio10;
            logCierreCiclo.PServicio11 = v.PServicio11;
            logCierreCiclo.PServicio12 = v.PServicio12;
            logCierreCiclo.PServicio13 = v.PServicio13;
            logCierreCiclo.PServicio14 = v.PServicio14;
            logCierreCiclo.PServicio15 = v.PServicio15;
            logCierreCiclo.PServicio16 = v.PServicio16;
            logCierreCiclo.PServicio17 = v.PServicio17;
            logCierreCiclo.PServicio18 = v.PServicio18;
            logCierreCiclo.PServicio19 = v.PServicio19;
            logCierreCiclo.PServicio20 = v.PServicio20;
            logCierreCiclo.PServicio21 = v.PServicio21;
            logCierreCiclo.PServicio22 = v.PServicio22;
            logCierreCiclo.PServicio23 = v.PServicio23;
            logCierreCiclo.PServicio24 = v.PServicio24;
            logCierreCiclo.PServicio25 = v.PServicio25;
            logCierreCiclo.PServicio26 = v.PServicio26;
            logCierreCiclo.PServicio27 = v.PServicio27;
            logCierreCiclo.PServicio28 = v.PServicio28;
            logCierreCiclo.PServicio29 = v.PServicio29;
            logCierreCiclo.PServicio3 = v.PServicio3;
            logCierreCiclo.PServicio30 = v.PServicio30;
            logCierreCiclo.PServicio31 = v.PServicio31;
            logCierreCiclo.PServicio32 = v.PServicio32;
            logCierreCiclo.PServicio33 = v.PServicio33;
            logCierreCiclo.PServicio34 = v.PServicio34;
            logCierreCiclo.PServicio35 = v.PServicio35;
            logCierreCiclo.PServicio36 = v.PServicio36;
            logCierreCiclo.PServicio4 = v.PServicio4;
            logCierreCiclo.PServicio5 = v.PServicio5;
            logCierreCiclo.PServicio6 = v.PServicio6;
            logCierreCiclo.PServicio7 = v.PServicio7;
            logCierreCiclo.PServicio8 = v.PServicio8;
            logCierreCiclo.PServicio9 = v.PServicio9;
            logCierreCiclo.Razon = v.Razon;
            logCierreCiclo.Seguimiento = v.Seguimiento;
            logCierreCiclo.TipoContacto = v.TipoContacto;
            logCierreCiclo.UsuarioGestion = v.UsuarioGestion;

            return logCierreCiclo;

        }
    }

}
// </auto-generated>
