// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;

namespace Telmexla.Servicios.DIME.Entity
{

    // TBL_LOG_DOCSIS_OVERLAP
    public class LogDocsisOverlap
    {
        public int Id { get; set; } // ID
        public System.DateTime? FechaGestion { get; set; } // FECHA_GESTION
        public string UsuarioGestion { get; set; } // USUARIO_GESTION (length: 50)
        public string AliadoGestion { get; set; } // ALIADO_GESTION (length: 50)
        public string OperacionGestion { get; set; } // OPERACION_GESTION (length: 50)
        public string NombreBase { get; set; } // NOMBRE_BASE (length: 50)
        public double? CuentaCliente { get; set; } // CUENTA_CLIENTE
        public string NombreCliente { get; set; } // NOMBRE_CLIENTE (length: 50)
        public string ApellidoCliente { get; set; } // APELLIDO_CLIENTE (length: 50)
        public string DireccionInstalacion { get; set; } // DIRECCION_INSTALACION (length: 100)
        public string DireccionCorrespondencia { get; set; } // DIRECCION_CORRESPONDENCIA (length: 100)
        public string CorreoElectronico { get; set; } // CORREO_ELECTRONICO (length: 100)
        public decimal? Telefono1 { get; set; } // TELEFONO_1
        public decimal? Telefono2 { get; set; } // TELEFONO_2
        public decimal? Telefono3 { get; set; } // TELEFONO_3
        public decimal? Movil1 { get; set; } // MOVIL_1
        public decimal? Movil2 { get; set; } // MOVIL_2
        public string PaqueteActual { get; set; } // PAQUETE_ACTUAL (length: 15)
        public string TipoDeContacto { get; set; } // TIPO_DE_CONTACTO (length: 100)
        public string Gestion { get; set; } // GESTION (length: 100)
        public string Cierre { get; set; } // CIERRE (length: 100)
        public string Razon { get; set; } // RAZON (length: 100)
        public string Observaciones { get; set; } // OBSERVACIONES (length: 200)
        public string NombreUsuarioGestion { get; set; } // NOMBRE_USUARIO_GESTION (length: 100)
        public string Aliado { get; set; } // ALIADO (length: 100)
        public string Seguimiento { get; set; } // SEGUIMIENTO (length: 2)
        public System.DateTime? FechaSeguimiento { get; set; } // FECHA_SEGUIMIENTO

        public static explicit operator LogDocsisOverlap(DocsisOverlap v)
        {
            LogDocsisOverlap logger = new LogDocsisOverlap();
            logger.Aliado = v.Aliado;
            logger.AliadoGestion = v.AliadoGestion;
            logger.ApellidoCliente = v.ApellidoCliente;
            logger.Cierre = v.Cierre;
            logger.CorreoElectronico = v.CorreoElectronico;
            logger.CuentaCliente = v.CuentaCliente;
            logger.DireccionCorrespondencia = v.DireccionCorrespondencia;
            logger.DireccionInstalacion = v.DireccionInstalacion;
            logger.FechaGestion = v.FechaGestion;
            logger.FechaSeguimiento = v.FechaSeguimiento;
            logger.Gestion = v.Gestion;
            logger.Id = v.Id;
            logger.Movil1 = v.Movil1;
            logger.Movil2 = v.Movil2;
            logger.NombreBase = v.NombreBase;
            logger.NombreCliente = v.NombreCliente;
            logger.NombreUsuarioGestion = v.NombreUsuarioGestion;
            logger.Observaciones = v.Observaciones;
            logger.OperacionGestion = v.OperacionGestion;
            logger.PaqueteActual = v.PaqueteActual;
            logger.Razon = v.Razon;
            logger.Seguimiento = v.Seguimiento;
            logger.Telefono1 = v.Telefono1;
            logger.Telefono2 = v.Telefono2;
            logger.Telefono3 = v.Telefono3;
            logger.TipoDeContacto = v.TipoDeContacto;
            logger.UsuarioGestion = v.UsuarioGestion;
            return logger;

        }
    }

}
// </auto-generated>
