// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Telmexla.Servicios.DIME.Entity
{

    // TBL_REGISTRO_SESION
    public class Rechazo
    {
        public decimal IdRechazo { get; set; } // ID_RECHAZO
        public decimal? IdIngreso { get; set; } // ID_INGRESO
        public System.DateTime? FechaCreacionCaso { get; set; } // FECHA_CREACION_CASO
        public string HoraCreacionCaso { get; set; } // HORA_CREACION_CASO (length: 50)
        public string UsuarioCreacionCaso { get; set; } // USUARIO_CREACION_CASO (length: 50)
        public string NotasRechazo { get; set; } // NOTAS_RECHAZO (length: 500)
        public string UsuarioRechaza { get; set; } // USUARIO_RECHAZA (length: 50)
        public System.DateTime? FechaRechazo { get; set; } // FECHA_RECHAZO
        public System.DateTime? HoraRechazo { get; set; } // HORA_RECHAZO
    }

}
// </auto-generated>
