// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // TBL_BALANCE_SCORE_CARD
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class BalanceScoreCardConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<BalanceScoreCard>
    {
        public BalanceScoreCardConfiguration()
            : this("dbo")
        {
        }

        public BalanceScoreCardConfiguration(string schema)
        {
            ToTable("TBL_BALANCE_SCORE_CARD", schema);
            HasKey(x => x.Cedula);

            Property(x => x.Cedula).HasColumnName(@"CEDULA").IsRequired().HasColumnType("numeric").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Nombre).HasColumnName(@"NOMBRE").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(100);
            Property(x => x.Aliado).HasColumnName(@"ALIADO").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(100);
            Property(x => x.Canal).HasColumnName(@"CANAL").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(100);
            Property(x => x.Operacion).HasColumnName(@"OPERACION").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(100);
            Property(x => x.Grupo).HasColumnName(@"GRUPO").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(100);
            Property(x => x.Cargo).HasColumnName(@"CARGO").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(100);
            Property(x => x.Segmento).HasColumnName(@"SEGMENTO").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(100);
            Property(x => x.Supervisor).HasColumnName(@"SUPERVISOR").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(100);
            Property(x => x.Acdcalls).HasColumnName(@"ACDCALLS").IsOptional().HasColumnType("numeric");
            Property(x => x.Tmo).HasColumnName(@"TMO").IsOptional().HasColumnType("numeric");
            Property(x => x.Espera).HasColumnName(@"ESPERA").IsOptional().HasColumnType("numeric");
            Property(x => x.Marcacion).HasColumnName(@"MARCACION").IsOptional().HasColumnType("numeric");
            Property(x => x.AjustesCorrecto).HasColumnName(@"AJUSTES_CORRECTO").IsOptional().HasColumnType("numeric");
            Property(x => x.PqrCorrectos).HasColumnName(@"PQR_CORRECTOS").IsOptional().HasColumnType("float");
            Property(x => x.MetaVentas).HasColumnName(@"META_VENTAS").IsOptional().HasColumnType("numeric");
            Property(x => x.ReincidenciaAsesor).HasColumnName(@"REINCIDENCIA_ASESOR").IsOptional().HasColumnType("numeric");
            Property(x => x.NpsSolucion).HasColumnName(@"NPS_SOLUCION").IsOptional().HasColumnType("numeric");
            Property(x => x.NpsSatisfaccion).HasColumnName(@"NPS_SATISFACCION").IsOptional().HasColumnType("numeric");
            Property(x => x.CalificacionMec).HasColumnName(@"CALIFICACION_MEC").IsOptional().HasColumnType("numeric");
            Property(x => x.ActivacionesClarovideo).HasColumnName(@"ACTIVACIONES_CLAROVIDEO").IsOptional().HasColumnType("numeric");
            Property(x => x.ActivacionesConvenioFactura).HasColumnName(@"ACTIVACIONES_CONVENIO_FACTURA").IsOptional().HasColumnType("numeric");
            Property(x => x.CalificacionTmo).HasColumnName(@"CALIFICACION_TMO").IsOptional().HasColumnType("numeric");
            Property(x => x.PuntajeTotal).HasColumnName(@"PUNTAJE_TOTAL").IsOptional().HasColumnType("numeric");
            Property(x => x.Fecha).HasColumnName(@"FECHA").IsOptional().HasColumnType("date");
            Property(x => x.Periodo).HasColumnName(@"PERIODO").IsOptional().HasColumnType("numeric");
            Property(x => x.PqrEscalados).HasColumnName(@"PQR_ESCALADOS").IsOptional().HasColumnType("float");
            Property(x => x.Reincidencia).HasColumnName(@"REINCIDENCIA").IsOptional().HasColumnType("float");
            Property(x => x.NpsRecomendacion).HasColumnName(@"NPS_RECOMENDACION").IsOptional().HasColumnType("float");
            Property(x => x.ActivacionClarovideo).HasColumnName(@"ACTIVACION_CLAROVIDEO").IsOptional().HasColumnType("float");
            Property(x => x.ActivacionConvenioFactura).HasColumnName(@"ACTIVACION_CONVENIO_FACTURA").IsOptional().HasColumnType("float");
            Property(x => x.NotaBuenServicio).HasColumnName(@"NOTA_BUEN_SERVICIO").IsOptional().HasColumnType("float");
            Property(x => x.PorcentajeCcaa).HasColumnName(@"PORCENTAJE_CCAA").IsOptional().HasColumnType("float");
        }
    }

}
// </auto-generated>
