// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // TBL_BALANCE_SCORE_CARD
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class BalanceScoreCard
    {
        public decimal Cedula { get; set; } // CEDULA (Primary key)
        public string Nombre { get; set; } // NOMBRE (length: 100)
        public string Aliado { get; set; } // ALIADO (length: 100)
        public string Canal { get; set; } // CANAL (length: 100)
        public string Operacion { get; set; } // OPERACION (length: 100)
        public string Grupo { get; set; } // GRUPO (length: 100)
        public string Cargo { get; set; } // CARGO (length: 100)
        public string Segmento { get; set; } // SEGMENTO (length: 100)
        public string Supervisor { get; set; } // SUPERVISOR (length: 100)
        public decimal? Acdcalls { get; set; } // ACDCALLS
        public decimal? Tmo { get; set; } // TMO
        public decimal? Espera { get; set; } // ESPERA
        public decimal? Marcacion { get; set; } // MARCACION
        public decimal? AjustesCorrecto { get; set; } // AJUSTES_CORRECTO
        public double? PqrCorrectos { get; set; } // PQR_CORRECTOS
        public decimal? MetaVentas { get; set; } // META_VENTAS
        public decimal? ReincidenciaAsesor { get; set; } // REINCIDENCIA_ASESOR
        public decimal? NpsSolucion { get; set; } // NPS_SOLUCION
        public decimal? NpsSatisfaccion { get; set; } // NPS_SATISFACCION
        public decimal? CalificacionMec { get; set; } // CALIFICACION_MEC
        public decimal? ActivacionesClarovideo { get; set; } // ACTIVACIONES_CLAROVIDEO
        public decimal? ActivacionesConvenioFactura { get; set; } // ACTIVACIONES_CONVENIO_FACTURA
        public decimal? CalificacionTmo { get; set; } // CALIFICACION_TMO
        public decimal? PuntajeTotal { get; set; } // PUNTAJE_TOTAL
        public System.DateTime? Fecha { get; set; } // FECHA
        public decimal? Periodo { get; set; } // PERIODO
        public double? PqrEscalados { get; set; } // PQR_ESCALADOS
        public double? Reincidencia { get; set; } // REINCIDENCIA
        public double? NpsRecomendacion { get; set; } // NPS_RECOMENDACION
        public double? ActivacionClarovideo { get; set; } // ACTIVACION_CLAROVIDEO
        public double? ActivacionConvenioFactura { get; set; } // ACTIVACION_CONVENIO_FACTURA
        public double? NotaBuenServicio { get; set; } // NOTA_BUEN_SERVICIO
        public double? PorcentajeCcaa { get; set; } // PORCENTAJE_CCAA
    }

}
// </auto-generated>
