// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // The table 'BASE_CUENTAS' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // BASE_CUENTAS
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class BaseCuenta
    {
        public double? Cuenta { get; set; } // CUENTA
        public double? HomePass { get; set; } // HOME_PASS
        public string Estado { get; set; } // ESTADO (length: 8)
        public string Nombre { get; set; } // NOMBRE (length: 100)
        public string Apellido { get; set; } // APELLIDO (length: 100)
        public string Cedula { get; set; } // CEDULA (length: 30)
        public double? TelefonoTelmex { get; set; } // TELEFONO_TELMEX
        public string Telefono1 { get; set; } // TELEFONO_1 (length: 30)
        public string Telefono2 { get; set; } // TELEFONO_2 (length: 30)
        public string Telefono3 { get; set; } // TELEFONO_3 (length: 30)
        public string Celular1 { get; set; } // CELULAR_1 (length: 30)
        public string Celular2 { get; set; } // CELULAR_2 (length: 30)
        public string TelefonoConv { get; set; } // TELEFONO_CONV (length: 100)
        public string DirInstalacion { get; set; } // DIR_INSTALACION (length: 200)
        public string DirCorrespondencia { get; set; } // DIR_CORRESPONDENCIA (length: 200)
        public string Correo { get; set; } // CORREO (length: 330)
        public string Nodo { get; set; } // NODO (length: 10)
        public string Red { get; set; } // RED (length: 100)
        public string Division { get; set; } // DIVISION (length: 100)
        public string Area { get; set; } // AREA (length: 100)
        public string Zona { get; set; } // ZONA (length: 100)
        public string Distrito { get; set; } // DISTRITO (length: 100)
        public string NombreComunidad { get; set; } // NOMBRE_COMUNIDAD (length: 100)
        public string Departamento { get; set; } // DEPARTAMENTO (length: 50)
        public string Estrato { get; set; } // ESTRATO (length: 15)
        public string TipoCliente { get; set; } // TIPO_CLIENTE (length: 15)
        public string Descripcion { get; set; } // DESCRIPCION (length: 100)
        public string GrupoSeg { get; set; } // GRUPO_SEG (length: 30)
        public string Productos { get; set; } // PRODUCTOS (length: 400)
        public string Clarovideo { get; set; } // CLAROVIDEO (length: 30)
        public string UsoCv { get; set; } // USO_CV (length: 30)
        public string ActivacionClaroVideo { get; set; } // ACTIVACION_CLARO_VIDEO (length: 5)
    }

}
// </auto-generated>
