// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // TBL_CONVENIO_ELECTRONICO
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class ConvenioElectronicoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ConvenioElectronico>
    {
        public ConvenioElectronicoConfiguration()
            : this("dbo")
        {
        }

        public ConvenioElectronicoConfiguration(string schema)
        {
            ToTable("TBL_CONVENIO_ELECTRONICO", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"ID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.FechaGestion).HasColumnName(@"FECHA_GESTION").IsOptional().HasColumnType("date");
            Property(x => x.HoraGestion).HasColumnName(@"HORA_GESTION").IsOptional().HasColumnType("datetime");
            Property(x => x.UsuarioGestion).HasColumnName(@"USUARIO_GESTION").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.AliadoGestion).HasColumnName(@"ALIADO_GESTION").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.LineaGestion).HasColumnName(@"LINEA_GESTION").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.CuentaCliente).HasColumnName(@"CUENTA_CLIENTE").IsOptional().HasColumnType("numeric");
            Property(x => x.NombreCliente).HasColumnName(@"NOMBRE_CLIENTE").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.ApellidoCliente).HasColumnName(@"APELLIDO_CLIENTE").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.DireccionInstalacion).HasColumnName(@"DIRECCION_INSTALACION").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(100);
            Property(x => x.DireccionCorrespondenciaActual).HasColumnName(@"DIRECCION_CORRESPONDENCIA_ACTUAL").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(100);
            Property(x => x.TelefonoTelmex).HasColumnName(@"TELEFONO_TELMEX").IsOptional().HasColumnType("numeric");
            Property(x => x.Telefono1).HasColumnName(@"TELEFONO_1").IsOptional().HasColumnType("numeric");
            Property(x => x.Telefono2).HasColumnName(@"TELEFONO_2").IsOptional().HasColumnType("numeric");
            Property(x => x.Telefono3).HasColumnName(@"TELEFONO_3").IsOptional().HasColumnType("numeric");
            Property(x => x.MovilActual).HasColumnName(@"MOVIL_ACTUAL").IsOptional().HasColumnType("numeric");
            Property(x => x.CorreoActual).HasColumnName(@"CORREO_ACTUAL").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(100);
            Property(x => x.TipoContacto).HasColumnName(@"TIPO_CONTACTO").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.Cierre).HasColumnName(@"CIERRE").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(100);
            Property(x => x.Razon).HasColumnName(@"RAZON").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(100);
            Property(x => x.MovilNuevo).HasColumnName(@"MOVIL_NUEVO").IsOptional().HasColumnType("numeric");
            Property(x => x.NuevoCorreo).HasColumnName(@"NUEVO_CORREO").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(100);
            Property(x => x.NuevaDireccionCorrespondencia).HasColumnName(@"NUEVA_DIRECCION_CORRESPONDENCIA").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(100);
            Property(x => x.Seguimiento).HasColumnName(@"SEGUIMIENTO").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(2);
            Property(x => x.FechaSeguimiento).HasColumnName(@"FECHA_SEGUIMIENTO").IsOptional().HasColumnType("datetime");
        }
    }

}
// </auto-generated>
