// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // deakloclpalo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class DeakloclpaloConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Deakloclpalo>
    {
        public DeakloclpaloConfiguration()
            : this("dbo")
        {
        }

        public DeakloclpaloConfiguration(string schema)
        {
            ToTable("deakloclpalo", schema);
            HasKey(x => x.RowNumber);

            Property(x => x.RowNumber).HasColumnName(@"RowNumber").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.EventClass).HasColumnName(@"EventClass").IsOptional().HasColumnType("int");
            Property(x => x.EventSequence).HasColumnName(@"EventSequence").IsOptional().HasColumnType("bigint");
            Property(x => x.IsSystem).HasColumnName(@"IsSystem").IsOptional().HasColumnType("int");
            Property(x => x.LoginName).HasColumnName(@"LoginName").IsOptional().HasColumnType("nvarchar").HasMaxLength(128);
            Property(x => x.LoginSid).HasColumnName(@"LoginSid").IsOptional().HasColumnType("image").HasMaxLength(2147483647);
            Property(x => x.Spid).HasColumnName(@"SPID").IsOptional().HasColumnType("int");
            Property(x => x.ServerName).HasColumnName(@"ServerName").IsOptional().HasColumnType("nvarchar").HasMaxLength(128);
            Property(x => x.SessionLoginName).HasColumnName(@"SessionLoginName").IsOptional().HasColumnType("nvarchar").HasMaxLength(128);
            Property(x => x.StartTime).HasColumnName(@"StartTime").IsOptional().HasColumnType("datetime");
            Property(x => x.TextData).HasColumnName(@"TextData").IsOptional().HasColumnType("ntext").IsMaxLength();
            Property(x => x.TransactionId).HasColumnName(@"TransactionID").IsOptional().HasColumnType("bigint");
            Property(x => x.ApplicationName).HasColumnName(@"ApplicationName").IsOptional().HasColumnType("nvarchar").HasMaxLength(128);
            Property(x => x.BigintData1).HasColumnName(@"BigintData1").IsOptional().HasColumnType("bigint");
            Property(x => x.BinaryData).HasColumnName(@"BinaryData").IsOptional().HasColumnType("image").HasMaxLength(2147483647);
            Property(x => x.ClientProcessId).HasColumnName(@"ClientProcessID").IsOptional().HasColumnType("int");
            Property(x => x.DatabaseId).HasColumnName(@"DatabaseID").IsOptional().HasColumnType("int");
            Property(x => x.DatabaseName).HasColumnName(@"DatabaseName").IsOptional().HasColumnType("nvarchar").HasMaxLength(128);
            Property(x => x.Duration).HasColumnName(@"Duration").IsOptional().HasColumnType("bigint");
            Property(x => x.EndTime).HasColumnName(@"EndTime").IsOptional().HasColumnType("datetime");
            Property(x => x.GroupId).HasColumnName(@"GroupID").IsOptional().HasColumnType("int");
            Property(x => x.HostName).HasColumnName(@"HostName").IsOptional().HasColumnType("nvarchar").HasMaxLength(128);
            Property(x => x.IntegerData).HasColumnName(@"IntegerData").IsOptional().HasColumnType("int");
            Property(x => x.IntegerData2).HasColumnName(@"IntegerData2").IsOptional().HasColumnType("int");
            Property(x => x.Mode).HasColumnName(@"Mode").IsOptional().HasColumnType("int");
            Property(x => x.NtDomainName).HasColumnName(@"NTDomainName").IsOptional().HasColumnType("nvarchar").HasMaxLength(128);
            Property(x => x.NtUserName).HasColumnName(@"NTUserName").IsOptional().HasColumnType("nvarchar").HasMaxLength(128);
            Property(x => x.ObjectId).HasColumnName(@"ObjectID").IsOptional().HasColumnType("int");
            Property(x => x.ObjectId2).HasColumnName(@"ObjectID2").IsOptional().HasColumnType("bigint");
            Property(x => x.OwnerId).HasColumnName(@"OwnerID").IsOptional().HasColumnType("int");
            Property(x => x.RequestId).HasColumnName(@"RequestID").IsOptional().HasColumnType("int");
            Property(x => x.Type).HasColumnName(@"Type").IsOptional().HasColumnType("int");
            Property(x => x.EventSubClass).HasColumnName(@"EventSubClass").IsOptional().HasColumnType("int");
        }
    }

}
// </auto-generated>
