// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // deakloclpalo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class Deakloclpalo
    {
        public int RowNumber { get; set; } // RowNumber (Primary key)
        public int? EventClass { get; set; } // EventClass
        public long? EventSequence { get; set; } // EventSequence
        public int? IsSystem { get; set; } // IsSystem
        public string LoginName { get; set; } // LoginName (length: 128)
        public byte[] LoginSid { get; set; } // LoginSid (length: 2147483647)
        public int? Spid { get; set; } // SPID
        public string ServerName { get; set; } // ServerName (length: 128)
        public string SessionLoginName { get; set; } // SessionLoginName (length: 128)
        public System.DateTime? StartTime { get; set; } // StartTime
        public string TextData { get; set; } // TextData (length: 1073741823)
        public long? TransactionId { get; set; } // TransactionID
        public string ApplicationName { get; set; } // ApplicationName (length: 128)
        public long? BigintData1 { get; set; } // BigintData1
        public byte[] BinaryData { get; set; } // BinaryData (length: 2147483647)
        public int? ClientProcessId { get; set; } // ClientProcessID
        public int? DatabaseId { get; set; } // DatabaseID
        public string DatabaseName { get; set; } // DatabaseName (length: 128)
        public long? Duration { get; set; } // Duration
        public System.DateTime? EndTime { get; set; } // EndTime
        public int? GroupId { get; set; } // GroupID
        public string HostName { get; set; } // HostName (length: 128)
        public int? IntegerData { get; set; } // IntegerData
        public int? IntegerData2 { get; set; } // IntegerData2
        public int? Mode { get; set; } // Mode
        public string NtDomainName { get; set; } // NTDomainName (length: 128)
        public string NtUserName { get; set; } // NTUserName (length: 128)
        public int? ObjectId { get; set; } // ObjectID
        public long? ObjectId2 { get; set; } // ObjectID2
        public int? OwnerId { get; set; } // OwnerID
        public int? RequestId { get; set; } // RequestID
        public int? Type { get; set; } // Type
        public int? EventSubClass { get; set; } // EventSubClass
    }

}
// </auto-generated>
