// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // TMP_DEPARTAMENTOS_CIUDADES
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class DepartamentosCiudade
    {
        public decimal Id { get; set; } // ID (Primary key)
        public string Departamento { get; set; } // DEPARTAMENTO (length: 100)
        public string NombreComunidad { get; set; } // NOMBRE_COMUNIDAD (length: 100)
        public string Comunidad { get; set; } // COMUNIDAD (length: 20)
        public string Red { get; set; } // RED (length: 50)
    }

}
// </auto-generated>
