// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // TBL_DISTRIBUCIONES_BLENDING
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class DistribucionesBlending
    {
        public decimal Id { get; set; } // ID (Primary key)
        public decimal CuentaCliente { get; set; } // CUENTA_CLIENTE
        public string FormularioDestino { get; set; } // FORMULARIO_DESTINO (length: 255)
        public string AliadoDestino { get; set; } // ALIADO_DESTINO (length: 255)
        public string OperacionDestino { get; set; } // OPERACION_DESTINO (length: 255)
        public string CampanaDestino { get; set; } // CAMPANA_DESTINO (length: 255)
        public int? UsuarioGestionando { get; set; } // USUARIO_GESTIONANDO
        public System.DateTime? FechaAsignacion { get; set; } // FECHA_ASIGNACION
        public string UsuarioAsignacion { get; set; } // USUARIO_ASIGNACION (length: 30)
    }

}
// </auto-generated>
