// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // TBL_DISTRIBUCIONES_BLENDING
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class DistribucionesBlendingConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<DistribucionesBlending>
    {
        public DistribucionesBlendingConfiguration()
            : this("dbo")
        {
        }

        public DistribucionesBlendingConfiguration(string schema)
        {
            ToTable("TBL_DISTRIBUCIONES_BLENDING", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"ID").IsRequired().HasColumnType("numeric").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.CuentaCliente).HasColumnName(@"CUENTA_CLIENTE").IsRequired().HasColumnType("numeric");
            Property(x => x.FormularioDestino).HasColumnName(@"FORMULARIO_DESTINO").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(255);
            Property(x => x.AliadoDestino).HasColumnName(@"ALIADO_DESTINO").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(255);
            Property(x => x.OperacionDestino).HasColumnName(@"OPERACION_DESTINO").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(255);
            Property(x => x.CampanaDestino).HasColumnName(@"CAMPANA_DESTINO").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(255);
            Property(x => x.UsuarioGestionando).HasColumnName(@"USUARIO_GESTIONANDO").IsOptional().HasColumnType("int");
            Property(x => x.FechaAsignacion).HasColumnName(@"FECHA_ASIGNACION").IsOptional().HasColumnType("datetime");
            Property(x => x.UsuarioAsignacion).HasColumnName(@"USUARIO_ASIGNACION").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(30);
        }
    }

}
// </auto-generated>
