// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // TMP_GBC_RENTABILIZACION
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class GbcRentabilizacion
    {
        public decimal Id { get; set; } // ID (Primary key)
        public decimal? CuentaCliente { get; set; } // CUENTA_CLIENTE
        public string ConsumosPpv { get; set; } // CONSUMOS_PPV (length: 255)
        public string UltimaPpv { get; set; } // ULTIMA_PPV (length: 255)
        public string SiembraHd { get; set; } // SIEMBRA_HD (length: 255)
        public string SiembraVoz { get; set; } // SIEMBRA_VOZ (length: 255)
        public string BlindajeInternet { get; set; } // BLINDAJE_INTERNET (length: 255)
        public string UltimaMarcacion { get; set; } // ULTIMA_MARCACION (length: 255)
        public string Ofrecimiento1 { get; set; } // OFRECIMIENTO_1 (length: 255)
        public string Ofrecimiento2 { get; set; } // OFRECIMIENTO_2 (length: 255)
        public string Ofrecimiento3 { get; set; } // OFRECIMIENTO_3 (length: 255)
        public string Campana1 { get; set; } // CAMPANA_1 (length: 255)
        public string Campana2 { get; set; } // CAMPANA_2 (length: 255)
        public string Campana3 { get; set; } // CAMPANA_3 (length: 255)
    }

}
// </auto-generated>
