// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // TBL_GBL_RENTABILIZACION
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class GblRentabilizacion
    {
        public decimal Id { get; set; } // ID (Primary key)
        public System.DateTime? FechaGestion { get; set; } // FECHA_GESTION
        public string UsuarioGestion { get; set; } // USUARIO_GESTION (length: 255)
        public string AliadoGestion { get; set; } // ALIADO_GESTION (length: 255)
        public string OperacionGestion { get; set; } // OPERACION_GESTION (length: 255)
        public decimal? CuentaCliente { get; set; } // CUENTA_CLIENTE
        public string ConsumosPpv { get; set; } // CONSUMOS_PPV (length: 255)
        public string UltimaPpv { get; set; } // ULTIMA_PPV (length: 255)
        public string SiembraHd { get; set; } // SIEMBRA_HD (length: 255)
        public string SiembraVoz { get; set; } // SIEMBRA_VOZ (length: 255)
        public string BlindajeInternet { get; set; } // BLINDAJE_INTERNET (length: 255)
        public string UltimaMarcacion { get; set; } // ULTIMA_MARCACION (length: 255)
        public string OfrecimientoAceptado { get; set; } // OFRECIMIENTO_ACEPTADO (length: 255)
        public string TipoContacto { get; set; } // TIPO_CONTACTO (length: 255)
        public string Gestion { get; set; } // GESTION (length: 255)
        public string Cierre { get; set; } // CIERRE (length: 255)
        public string Causa { get; set; } // CAUSA (length: 255)
        public string Motivo { get; set; } // MOTIVO (length: 255)
        public string Observaciones { get; set; } // OBSERVACIONES (length: 1000)
        public System.DateTime? FechaSeguimiento { get; set; } // FECHA_SEGUIMIENTO
    }

}
// </auto-generated>
