// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // TBL_GBP_FUERA_NIVELES
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class GbpFueraNivele
    {
        public decimal Id { get; set; } // ID (Primary key)
        public System.DateTime? FechaGestion { get; set; } // FECHA_GESTION
        public string UsuarioGestion { get; set; } // USUARIO_GESTION (length: 50)
        public string AliadoGestion { get; set; } // ALIADO_GESTION (length: 50)
        public decimal? CuentaCliente { get; set; } // CUENTA_CLIENTE
        public string NombreCliente { get; set; } // NOMBRE_CLIENTE (length: 255)
        public string ApellidoCliente { get; set; } // APELLIDO_CLIENTE (length: 255)
        public string DireccionInstalacion { get; set; } // DIRECCION_INSTALACION (length: 255)
        public string DireccionCorrespondencia { get; set; } // DIRECCION_CORRESPONDENCIA (length: 255)
        public string Telefono1 { get; set; } // TELEFONO_1 (length: 255)
        public string Telefono2 { get; set; } // TELEFONO_2 (length: 255)
        public string Telefono3 { get; set; } // TELEFONO_3 (length: 255)
        public string Movil1 { get; set; } // MOVIL_1 (length: 255)
        public string Movil2 { get; set; } // MOVIL_2 (length: 255)
        public string MovilPostpago { get; set; } // MOVIL_POSTPAGO (length: 255)
        public string CorreoActual { get; set; } // CORREO_ACTUAL (length: 255)
        public string EstratoCliente { get; set; } // ESTRATO_CLIENTE (length: 255)
        public string ServiciosActuales { get; set; } // SERVICIOS_ACTUALES (length: 255)
        public string Nodo { get; set; } // NODO (length: 255)
        public string NombreComunidad { get; set; } // NOMBRE_COMUNIDAD (length: 255)
        public string Division { get; set; } // DIVISION (length: 255)
        public string TipoCliente { get; set; } // TIPO_CLIENTE (length: 255)
        public string DescripcionTpc { get; set; } // DESCRIPCION_TPC (length: 255)
        public string Cmts { get; set; } // CMTS (length: 255)
        public string TipoModem { get; set; } // TIPO_MODEM (length: 255)
        public int? Prioridad { get; set; } // PRIORIDAD
        public string TipoDeContacto { get; set; } // TIPO_DE_CONTACTO (length: 255)
        public string Gestion { get; set; } // GESTION (length: 255)
        public string Cierre { get; set; } // CIERRE (length: 255)
        public string Razon { get; set; } // RAZON (length: 255)
        public System.DateTime? FechaSeguimiento { get; set; } // FECHA_SEGUIMIENTO
        public string Observaciones { get; set; } // OBSERVACIONES (length: 1000)
    }

}
// </auto-generated>
