// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // TBL_GESTION_MATRICES
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class GestionMatrIx
    {
        public decimal Id { get; set; } // ID (Primary key)
        public decimal IdTransaccion { get; set; } // ID_TRANSACCION
        public string UsuarioTransaccion { get; set; } // USUARIO_TRANSACCION (length: 30)
        public string CanalTransaccion { get; set; } // CANAL_TRANSACCION (length: 50)
        public System.DateTime? FechaTransaccion { get; set; } // FECHA_TRANSACCION
        public string NombreLineaTransaccion { get; set; } // NOMBRE_LINEA_TRANSACCION (length: 100)
        public string TipoGestionMatriz { get; set; } // TIPO_GESTION_MATRIZ (length: 30)
        public string TipoCliente { get; set; } // TIPO_CLIENTE (length: 5)
        public decimal? CuentaCliente { get; set; } // CUENTA_CLIENTE
        public decimal? CuentaMatriz { get; set; } // CUENTA_MATRIZ
        public decimal? OrdenDeTrabajo { get; set; } // ORDEN_DE_TRABAJO
        public string Direccion { get; set; } // DIRECCION (length: 255)
        public string Nodo { get; set; } // NODO (length: 15)
        public string NombreConjuntoEdificio { get; set; } // NOMBRE_CONJUNTO_EDIFICIO (length: 100)
        public string TelefonoCliente { get; set; } // TELEFONO_CLIENTE (length: 20)
        public string TelefonoAdministrador { get; set; } // TELEFONO_ADMINISTRADOR (length: 20)
        public string NombreAdministrador { get; set; } // NOMBRE_ADMINISTRADOR (length: 100)
        public string Razon { get; set; } // RAZON (length: 100)
        public string Subrazon { get; set; } // SUBRAZON (length: 100)
        public string Observacion { get; set; } // OBSERVACION (length: 1073741823)
        public string EstadoTransaccion { get; set; } // ESTADO_TRANSACCION (length: 30)
        public string UsuarioBackofficeCreacion { get; set; } // USUARIO_BACKOFFICE_CREACION (length: 30)
        public string UsuarioBackofficeGestion { get; set; } // USUARIO_BACKOFFICE_GESTION (length: 30)

        // Foreign keys
        public virtual TransaccionesTraslado TransaccionesTraslado_IdTransaccion { get; set; } // FK__TBL_GESTI__ID_TR__02C769E9
        public virtual TransaccionesTraslado TransaccionesTraslado1 { get; set; } // FK__TBL_GESTI__ID_TR__7C1A6C5A
    }

}
// </auto-generated>
