// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // The table 'TMP_ID_ID_NOTAS_INGRESO' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // TMP_ID_ID_NOTAS_INGRESO
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class IdIdNotasIngreso
    {
        public decimal? IdIngreso { get; set; } // ID_INGRESO
    }

}
// </auto-generated>
