// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // TBL_INFORMACION_NODOS
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class InformacionNodo
    {
        public decimal IdNodo { get; set; } // ID_NODO (Primary key)
        public string Nodo { get; set; } // NODO (length: 255)
        public string NombreNodo { get; set; } // NOMBRE_NODO (length: 255)
        public string Div { get; set; } // DIV (length: 255)
        public string Com { get; set; } // COM (length: 255)
        public decimal? Divisional { get; set; } // DIVISIONAL
        public decimal? Area { get; set; } // AREA
        public decimal? Distrito { get; set; } // DISTRITO
        public decimal? Ugestion { get; set; } // UGESTION
        public string Usuario { get; set; } // USUARIO (length: 255)
        public System.DateTime? FechaCreacion { get; set; } // FECHA_CREACION
        public string Estado { get; set; } // ESTADO (length: 255)
        public string Red { get; set; } // RED (length: 255)
        public string Aliado { get; set; } // ALIADO (length: 255)
    }

}
// </auto-generated>
