// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // TBL_INFORMACION_NODOS
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class InformacionNodoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<InformacionNodo>
    {
        public InformacionNodoConfiguration()
            : this("dbo")
        {
        }

        public InformacionNodoConfiguration(string schema)
        {
            ToTable("TBL_INFORMACION_NODOS", schema);
            HasKey(x => x.IdNodo);

            Property(x => x.IdNodo).HasColumnName(@"ID_NODO").IsRequired().HasColumnType("numeric").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Nodo).HasColumnName(@"NODO").IsOptional().HasColumnType("nvarchar").HasMaxLength(255);
            Property(x => x.NombreNodo).HasColumnName(@"NOMBRE_NODO").IsOptional().HasColumnType("nvarchar").HasMaxLength(255);
            Property(x => x.Div).HasColumnName(@"DIV").IsOptional().HasColumnType("nvarchar").HasMaxLength(255);
            Property(x => x.Com).HasColumnName(@"COM").IsOptional().HasColumnType("nvarchar").HasMaxLength(255);
            Property(x => x.Divisional).HasColumnName(@"DIVISIONAL").IsOptional().HasColumnType("numeric");
            Property(x => x.Area).HasColumnName(@"AREA").IsOptional().HasColumnType("numeric");
            Property(x => x.Distrito).HasColumnName(@"DISTRITO").IsOptional().HasColumnType("numeric");
            Property(x => x.Ugestion).HasColumnName(@"UGESTION").IsOptional().HasColumnType("numeric");
            Property(x => x.Usuario).HasColumnName(@"USUARIO").IsOptional().HasColumnType("nvarchar").HasMaxLength(255);
            Property(x => x.FechaCreacion).HasColumnName(@"FECHA_CREACION").IsOptional().HasColumnType("datetime");
            Property(x => x.Estado).HasColumnName(@"ESTADO").IsOptional().HasColumnType("nvarchar").HasMaxLength(255);
            Property(x => x.Red).HasColumnName(@"RED").IsOptional().HasColumnType("nvarchar").HasMaxLength(255);
            Property(x => x.Aliado).HasColumnName(@"ALIADO").IsOptional().HasColumnType("nvarchar").HasMaxLength(255);
        }
    }

}
// </auto-generated>
