// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // TBL_INGRESOS_TRASLADOS
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class IngresosTraslado
    {
        public decimal IdTraslado { get; set; } // ID_TRASLADO (Primary key)
        public decimal CuentaCliente { get; set; } // CUENTA_CLIENTE
        public string Direccion { get; set; } // DIRECCION (length: 200)
        public string Estrato { get; set; } // ESTRATO (length: 50)
        public string Nodo { get; set; } // NODO (length: 15)
        public string TelefonoCelular { get; set; } // TELEFONO_CELULAR (length: 20)
        public string TelefonoFijo { get; set; } // TELEFONO_FIJO (length: 20)
        public System.DateTime? FechaApertura { get; set; } // FECHA_APERTURA
        public System.DateTime? HoraApertura { get; set; } // HORA_APERTURA
        public System.DateTime? FechaCierre { get; set; } // FECHA_CIERRE
        public System.DateTime? HoraCierre { get; set; } // HORA_CIERRE
        public string UsuarioApertura { get; set; } // USUARIO_APERTURA (length: 100)
        public string UsuarioCierre { get; set; } // USUARIO_CIERRE (length: 100)
        public System.DateTime? FechaUltimaActualizacion { get; set; } // FECHA_ULTIMA_ACTUALIZACION
        public string UsuarioUltimaActualizacion { get; set; } // USUARIO_ULTIMA_ACTUALIZACION (length: 100)
        public System.DateTime? HoraUltimaActualizacion { get; set; } // HORA_ULTIMA_ACTUALIZACION
        public string Razon { get; set; } // RAZON (length: 100)
        public string Subrazon { get; set; } // SUBRAZON (length: 100)
        public string EstadoCaso { get; set; } // ESTADO_CASO (length: 30)
        public string EstadoBackoffice { get; set; } // ESTADO_BACKOFFICE (length: 30)
        public string UsuarioBackoffice { get; set; } // USUARIO_BACKOFFICE (length: 50)
        public System.DateTime? FechaInicioGestionBackoffice { get; set; } // FECHA_INICIO_GESTION_BACKOFFICE
        public string UsuarioGestionOutbound { get; set; } // USUARIO_GESTION_OUTBOUND (length: 30)
        public System.DateTime? FechaInicioGestionOutbound { get; set; } // FECHA_INICIO_GESTION_OUTBOUND
        public string AliadoApertura { get; set; } // ALIADO_APERTURA (length: 50)
        public string NombreLineaIngreso { get; set; } // NOMBRE_LINEA_INGRESO (length: 50)
        public string NombreLineaEscalado { get; set; } // NOMBRE_LINEA_ESCALADO (length: 50)

        // Reverse navigation
        public virtual IngresosTraslado IngresosTraslado2 { get; set; } // TBL_INGRESOS_TRASLADOS.FK__TBL_INGRE__ID_TR__19DFD96B
        public virtual IngresosTraslado IngresosTraslado4 { get; set; } // TBL_INGRESOS_TRASLADOS.FK__TBL_INGRE__ID_TR__1CBC4616

        // Foreign keys
        public virtual IngresosTraslado IngresosTraslado1 { get; set; } // FK__TBL_INGRE__ID_TR__19DFD96B
        public virtual IngresosTraslado IngresosTraslado3 { get; set; } // FK__TBL_INGRE__ID_TR__1CBC4616
    }

}
// </auto-generated>
