// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // TBL_LIBERACION_DE_HOMEPASS
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class LiberacionDeHomepass
    {
        public decimal Id { get; set; } // ID (Primary key)
        public decimal IdTransaccion { get; set; } // ID_TRANSACCION
        public string UsuarioTransaccion { get; set; } // USUARIO_TRANSACCION (length: 30)
        public string CanalTransaccion { get; set; } // CANAL_TRANSACCION (length: 50)
        public System.DateTime? FechaTransaccion { get; set; } // FECHA_TRANSACCION
        public string NombreLineaTransaccion { get; set; } // NOMBRE_LINEA_TRANSACCION (length: 100)
        public decimal? CuentaQueOcupa { get; set; } // CUENTA_QUE_OCUPA
        public decimal? CuentaQueTraslada { get; set; } // CUENTA_QUE_TRASLADA
        public string Direccion { get; set; } // DIRECCION (length: 255)
        public string Nodo { get; set; } // NODO (length: 15)
        public string TelefonoCelular { get; set; } // TELEFONO_CELULAR (length: 20)
        public string TelefonoFijo { get; set; } // TELEFONO_FIJO (length: 20)
        public string Razon { get; set; } // RAZON (length: 100)
        public string Subrazon { get; set; } // SUBRAZON (length: 100)
        public string Observacion { get; set; } // OBSERVACION (length: 1073741823)
        public string EstadoTransaccion { get; set; } // ESTADO_TRANSACCION (length: 30)
        public string UsuarioBackoffice { get; set; } // USUARIO_BACKOFFICE (length: 30)
        public string MotivoLiberacion { get; set; } // MOTIVO_LIBERACION (length: 100)

        // Foreign keys
        public virtual TransaccionesTraslado TransaccionesTraslado { get; set; } // FK__TBL_LIBER__ID_TR__76619304
    }

}
// </auto-generated>
