// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // The table 'TBL_LOG_CARGUE_TABLAS' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // TBL_LOG_CARGUE_TABLAS
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class LogCargueTabla
    {
        public string NombreTabla { get; set; } // NOMBRE_TABLA (length: 128)
        public string Esquema { get; set; } // ESQUEMA (length: 128)
        public long? NumeroFilas { get; set; } // NUMERO_FILAS
        public System.DateTime? FechaCreacion { get; set; } // FECHA_CREACION
        public System.DateTime? FechaModificacion { get; set; } // FECHA_MODIFICACION
        public long? EspacioTotalKb { get; set; } // ESPACIO_TOTAL_KB
        public long? EspacioUsadoKb { get; set; } // ESPACIO_USADO_KB
        public long? EspacionousadoKb { get; set; } // ESPACIONOUSADO_KB
        public string FechaCargue { get; set; } // FECHA_CARGUE (length: 10)
        public string HoraCargue { get; set; } // HORA_CARGUE (length: 8)
        public string Base { get; set; } // BASE (length: 50)
    }

}
// </auto-generated>
