// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // MAESTRO_DIVISIONAL
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class MaestroDivisional
    {
        public int Id { get; set; } // ID (Primary key)
        public string IdNodo { get; set; } // ID NODO (length: 100)
        public string NombreNodo { get; set; } // NOMBRE_NODO (length: 100)
        public string Comunidad { get; set; } // COMUNIDAD (length: 100)
        public string NombreComunidad { get; set; } // NOMBRE_COMUNIDAD (length: 100)
        public string Departamento { get; set; } // DEPARTAMENTO (length: 100)
        public string CodigoDane { get; set; } // CODIGO_DANE (length: 100)
        public string Estatus { get; set; } // ESTATUS (length: 100)
        public string Red { get; set; } // RED (length: 100)
        public double? HhppBi { get; set; } // HHPP_BI
        public double? Hogares { get; set; } // HOGARES
        public double? Servicios { get; set; } // SERVICIOS
        public double? IdRegional { get; set; } // ID_REGIONAL
        public string Regional { get; set; } // REGIONAL (length: 100)
        public string IdArea { get; set; } // ID_AREA (length: 100)
        public string Area { get; set; } // AREA (length: 100)
        public string IdZona { get; set; } // ID_ZONA (length: 100)
        public string Zona { get; set; } // ZONA (length: 100)
        public string IdDistrito { get; set; } // ID_DISTRITO (length: 100)
        public string Distrito { get; set; } // DISTRITO (length: 100)
        public string IdUnidadGestion { get; set; } // ID_UNIDAD GESTION (length: 100)
        public string IdUnidadGestion2 { get; set; } // ID_UNIDAD GESTION_2 (length: 100)
        public string Codigo { get; set; } // CODIGO (length: 100)
        public string Aliado { get; set; } // ALIADO (length: 100)
        public string TipologiaRed { get; set; } // TIPOLOGIA_RED (length: 100)
        public string EstadoNodo { get; set; } // ESTADO_NODO (length: 100)
        public string Proyecciones { get; set; } // PROYECCIONES (length: 100)
    }

}
// </auto-generated>
