// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // MAESTRO_RAZON
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class MaestroRazonConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<MaestroRazon>
    {
        public MaestroRazonConfiguration()
            : this("dbo")
        {
        }

        public MaestroRazonConfiguration(string schema)
        {
            ToTable("MAESTRO_RAZON", schema);
            HasKey(x => x.IdRazon);

            Property(x => x.IdRazon).HasColumnName(@"ID_RAZON").IsRequired().HasColumnType("numeric");
            Property(x => x.IdCierre).HasColumnName(@"ID_CIERRE").IsOptional().HasColumnType("numeric");
            Property(x => x.Razon).HasColumnName(@"RAZON").IsOptional().HasColumnType("ntext").IsMaxLength();
        }
    }

}
// </auto-generated>
