// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // MAESTRO_ESTADO_MARCACION
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class MaestroEstadoMarcacionConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<MaestroEstadoMarcacion>
    {
        public MaestroEstadoMarcacionConfiguration()
            : this("dbo")
        {
        }

        public MaestroEstadoMarcacionConfiguration(string schema)
        {
            ToTable("MAESTRO_ESTADO_MARCACION", schema);
            HasKey(x => x.IdEstado);

            Property(x => x.IdEstado).HasColumnName(@"ID_ESTADO").IsRequired().HasColumnType("numeric");
            Property(x => x.Estado).HasColumnName(@"ESTADO").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(8);
        }
    }

}
// </auto-generated>
