// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // MAESTRO_OUTBOUND_CIERRE_2
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class MaestroOutboundCierre2Configuration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<MaestroOutboundCierre2>
    {
        public MaestroOutboundCierre2Configuration()
            : this("dbo")
        {
        }

        public MaestroOutboundCierre2Configuration(string schema)
        {
            ToTable("MAESTRO_OUTBOUND_CIERRE_2", schema);
            HasKey(x => new { x.IdCierre, x.IdTipoContacto, x.Cierre });

            Property(x => x.IdCierre).HasColumnName(@"ID_CIERRE").IsRequired().HasColumnType("numeric").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.IdTipoContacto).HasColumnName(@"ID_TIPO_CONTACTO").IsRequired().HasColumnType("numeric");
            Property(x => x.Cierre).HasColumnName(@"CIERRE").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(100);
        }
    }

}
// </auto-generated>
