// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // MAESTRO_OUTBOUND_MOTIVO
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class MaestroOutboundMotivo
    {
        public decimal IdMotivo { get; set; } // ID_MOTIVO (Primary key)
        public decimal IdCausa { get; set; } // ID_CAUSA
        public string Motivo { get; set; } // MOTIVO (length: 100)

        // Foreign keys
        public virtual MaestroOutboundCausa MaestroOutboundCausa { get; set; } // FK__MAESTRO_O__ID_CA__5555A4F4
    }

}
// </auto-generated>
