// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // MAESTRO_CAUSAS
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class MaestroCausaConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<MaestroCausa>
    {
        public MaestroCausaConfiguration()
            : this("dbo")
        {
        }

        public MaestroCausaConfiguration(string schema)
        {
            ToTable("MAESTRO_CAUSAS", schema);
            HasKey(x => new { x.IdCausa, x.Causa });

            Property(x => x.IdCausa).HasColumnName(@"ID_CAUSA").IsRequired().HasColumnType("numeric");
            Property(x => x.IdHipotesis).HasColumnName(@"ID_HIPOTESIS").IsOptional().HasColumnType("numeric");
            Property(x => x.Causa).HasColumnName(@"CAUSA").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(100);
        }
    }

}
// </auto-generated>
