// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // MAESTRO_OUTBOUND_CAUSA
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class MaestroOutboundCausaConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<MaestroOutboundCausa>
    {
        public MaestroOutboundCausaConfiguration()
            : this("dbo")
        {
        }

        public MaestroOutboundCausaConfiguration(string schema)
        {
            ToTable("MAESTRO_OUTBOUND_CAUSA", schema);
            HasKey(x => x.IdCausa);

            Property(x => x.IdCausa).HasColumnName(@"ID_CAUSA").IsRequired().HasColumnType("numeric").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.IdRazon).HasColumnName(@"ID_RAZON").IsRequired().HasColumnType("numeric");
            Property(x => x.Causa).HasColumnName(@"CAUSA").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(100);

            // Foreign keys
            HasRequired(a => a.MaestroOutboundRazon).WithMany(b => b.MaestroOutboundCausas).HasForeignKey(c => c.IdRazon).WillCascadeOnDelete(false); // FK__MAESTRO_O__ID_RA__1881A0DE
        }
    }

}
// </auto-generated>
