// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // MAESTRO_ATRIBUTOS
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class MaestroAtributoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<MaestroAtributo>
    {
        public MaestroAtributoConfiguration()
            : this("dbo")
        {
        }

        public MaestroAtributoConfiguration(string schema)
        {
            ToTable("MAESTRO_ATRIBUTOS", schema);
            HasKey(x => new { x.IdAtributo, x.Servicio });

            Property(x => x.IdAtributo).HasColumnName(@"ID_ATRIBUTO").IsRequired().HasColumnType("numeric");
            Property(x => x.Servicio).HasColumnName(@"SERVICIO").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.Atributo).HasColumnName(@"ATRIBUTO").IsOptional().HasColumnType("ntext").IsMaxLength();
        }
    }

}
// </auto-generated>
