// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // MUNICIPIOS
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class MunicipioConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Municipio>
    {
        public MunicipioConfiguration()
            : this("dbo")
        {
        }

        public MunicipioConfiguration(string schema)
        {
            ToTable("MUNICIPIOS", schema);
            HasKey(x => x.IdMunicipio);

            Property(x => x.IdMunicipio).HasColumnName(@"ID_MUNICIPIO").IsRequired().HasColumnType("numeric").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.IdDepartamento).HasColumnName(@"ID_DEPARTAMENTO").IsOptional().HasColumnType("numeric");
            Property(x => x.Municipio_).HasColumnName(@"MUNICIPIO").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);

            // Foreign keys
            HasOptional(a => a.Departamento).WithMany(b => b.Municipios).HasForeignKey(c => c.IdDepartamento).WillCascadeOnDelete(false); // FK__MUNICIPIO__MUNIC__5F492382
        }
    }

}
// </auto-generated>
