// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // MUNICIPIOS
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class Municipio
    {
        public decimal IdMunicipio { get; set; } // ID_MUNICIPIO (Primary key)
        public decimal? IdDepartamento { get; set; } // ID_DEPARTAMENTO
        public string Municipio_ { get; set; } // MUNICIPIO (length: 50)

        // Foreign keys
        public virtual Departamento Departamento { get; set; } // FK__MUNICIPIO__MUNIC__5F492382
    }

}
// </auto-generated>
