// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // The table 'TMP_NODOS_ACTUALES' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // TMP_NODOS_ACTUALES
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class NodosActuale
    {
        public string Nodo { get; set; } // NODO (length: 100)
        public string NombreNodo { get; set; } // NOMBRE_NODO (length: 100)
        public string Div { get; set; } // DIV (length: 100)
        public string Com { get; set; } // COM (length: 100)
        public double? Divisional { get; set; } // DIVISIONAL
        public double? Area { get; set; } // AREA
        public double? Zona { get; set; } // ZONA
        public string Distrito { get; set; } // DISTRITO (length: 100)
        public double? Ugestion { get; set; } // UGESTION
        public string Usuario { get; set; } // USUARIO (length: 100)
        public string Estado { get; set; } // ESTADO (length: 100)
        public string Red { get; set; } // RED (length: 100)
        public string Aliado { get; set; } // ALIADO (length: 100)
    }

}
// </auto-generated>
