// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // ROL_USUARIO
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class RolUsuarioConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<RolUsuario>
    {
        public RolUsuarioConfiguration()
            : this("dbo")
        {
        }

        public RolUsuarioConfiguration(string schema)
        {
            ToTable("ROL_USUARIO", schema);
            HasKey(x => new { x.IdRol, x.Descripcion });

            Property(x => x.IdRol).HasColumnName(@"ID_ROL").IsRequired().HasColumnType("int");
            Property(x => x.Descripcion).HasColumnName(@"DESCRIPCION").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(100);
        }
    }

}
// </auto-generated>
