// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // SERVICIOS
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class ServicioConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Servicio>
    {
        public ServicioConfiguration()
            : this("dbo")
        {
        }

        public ServicioConfiguration(string schema)
        {
            ToTable("SERVICIOS", schema);
            HasKey(x => x.IdServicio);

            Property(x => x.IdServicio).HasColumnName(@"ID_SERVICIO").IsRequired().HasColumnType("int");
            Property(x => x.Descripcion).HasColumnName(@"DESCRIPCION").IsOptional().HasColumnType("nvarchar").HasMaxLength(255);
        }
    }

}
// </auto-generated>
