// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // The table 'TMP7_PQR_MAESTRO_FESTIVOS' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // TMP7_PQR_MAESTRO_FESTIVOS
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class Tmp7PqrMaestroFestivo
    {
        public string Id { get; set; } // ID (length: 20)
        public System.DateTime? Fecha { get; set; } // FECHA
        public string FechaRr { get; set; } // FECHA_RR (length: 100)
        public string NumeroDia { get; set; } // NUMERO_DIA (length: 100)
        public string NombreDia { get; set; } // NOMBRE_DIA (length: 255)
        public string NumeroMes { get; set; } // NUMERO_MES (length: 100)
        public string NombreMes { get; set; } // NOMBRE_MES (length: 255)
        public string Ano { get; set; } // ANO (length: 100)
        public string TipoDia { get; set; } // TIPO_DIA (length: 255)
        public string TipoDiaFestivo { get; set; } // TIPO_DIA_FESTIVO (length: 255)
        public string Semana { get; set; } // SEMANA (length: 255)
    }

}
// </auto-generated>
