// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // TBL_TRANSACCIONES_TRASLADOS
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class TransaccionesTraslado
    {
        public decimal IdTransaccion { get; set; } // ID_TRANSACCION (Primary key)
        public decimal CuentaCliente { get; set; } // CUENTA_CLIENTE
        public string TipoDeGestion { get; set; } // TIPO_DE_GESTION (length: 50)
        public System.DateTime? FechaApertura { get; set; } // FECHA_APERTURA
        public System.DateTime? HoraApertura { get; set; } // HORA_APERTURA
        public System.DateTime? FechaCierre { get; set; } // FECHA_CIERRE
        public System.DateTime? HoraCierre { get; set; } // HORA_CIERRE
        public string UsuarioApertura { get; set; } // USUARIO_APERTURA (length: 100)
        public string UsuarioCierre { get; set; } // USUARIO_CIERRE (length: 100)
        public System.DateTime? FechaUltimaActualizacion { get; set; } // FECHA_ULTIMA_ACTUALIZACION
        public System.DateTime? HoraUltimaActualizacion { get; set; } // HORA_ULTIMA_ACTUALIZACION
        public string UsuarioUltimaActualizacion { get; set; } // USUARIO_ULTIMA_ACTUALIZACION (length: 100)
        public string EstadoTransaccion { get; set; } // ESTADO_TRANSACCION (length: 30)
        public string AliadoApertura { get; set; } // ALIADO_APERTURA (length: 50)
        public string NombreLineaIngreso { get; set; } // NOMBRE_LINEA_INGRESO (length: 50)
        public string NombreLineaEscalado { get; set; } // NOMBRE_LINEA_ESCALADO (length: 50)

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<CambioDeEstrato> CambioDeEstratoes { get; set; } // TBL_CAMBIO_DE_ESTRATO.FK__TBL_CAMBI__ID_TR__4DE98D56
        public virtual System.Collections.Generic.ICollection<CreacionDireccion> CreacionDireccions { get; set; } // TBL_CREACION_DIRECCION.FK__TBL_CREAC__ID_TR__4B0D20AB
        public virtual System.Collections.Generic.ICollection<GestionMatrIx> GestionMatrIces_IdTransaccion { get; set; } // TBL_GESTION_MATRICES.FK__TBL_GESTI__ID_TR__473C8FC7
        public virtual System.Collections.Generic.ICollection<GestionMatrIx> GestionMatrIces1 { get; set; } // TBL_GESTION_MATRICES.FK__TBL_GESTI__ID_TR__4830B400
        public virtual System.Collections.Generic.ICollection<LiberacionDeHomepass> LiberacionDeHomepasses { get; set; } // TBL_LIBERACION_DE_HOMEPASS.FK__TBL_LIBER__ID_TR__4460231C

        public TransaccionesTraslado()
        {
            CambioDeEstratoes = new System.Collections.Generic.List<CambioDeEstrato>();
            CreacionDireccions = new System.Collections.Generic.List<CreacionDireccion>();
            GestionMatrIces_IdTransaccion = new System.Collections.Generic.List<GestionMatrIx>();
            GestionMatrIces1 = new System.Collections.Generic.List<GestionMatrIx>();
            LiberacionDeHomepasses = new System.Collections.Generic.List<LiberacionDeHomepass>();
        }
    }

}
// </auto-generated>
