// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // TBL_TRASLADO_FALLIDO
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class TrasladoFallido
    {
        public decimal Id { get; set; } // ID (Primary key)
        public decimal IdTransaccion { get; set; } // ID_TRANSACCION
        public string UsuarioTransaccion { get; set; } // USUARIO_TRANSACCION (length: 30)
        public string CanalTransaccion { get; set; } // CANAL_TRANSACCION (length: 50)
        public System.DateTime? FechaTransaccion { get; set; } // FECHA_TRANSACCION
        public string NombreLineaTransaccion { get; set; } // NOMBRE_LINEA_TRANSACCION (length: 100)
        public string MotivoTrasladoFallido { get; set; } // MOTIVO_TRASLADO_FALLIDO (length: 100)
        public decimal? CuentaCliente { get; set; } // CUENTA_CLIENTE
        public decimal? CuentaOcupada { get; set; } // CUENTA_OCUPADA
        public decimal? CuentaTraslada { get; set; } // CUENTA_TRASLADA
        public decimal? CuentaMatriz { get; set; } // CUENTA_MATRIZ
        public string NombreConjuntoEdificio { get; set; } // NOMBRE_CONJUNTO_EDIFICIO (length: 255)
        public string EstadoMatriz { get; set; } // ESTADO_MATRIZ (length: 255)
        public string Direccion { get; set; } // DIRECCION (length: 255)
        public string Departamento { get; set; } // DEPARTAMENTO (length: 100)
        public string NombreComunidad { get; set; } // NOMBRE_COMUNIDAD (length: 100)
        public string Comunidad { get; set; } // COMUNIDAD (length: 20)
        public string Red { get; set; } // RED (length: 50)
        public string EstratoOrigen { get; set; } // ESTRATO_ORIGEN (length: 50)
        public string EstratoDestino { get; set; } // ESTRATO_DESTINO (length: 50)
        public string TarifaActual { get; set; } // TARIFA_ACTUAL (length: 20)
        public string TarifaNueva { get; set; } // TARIFA_NUEVA (length: 20)
        public string GestionPorTraslado { get; set; } // GESTION_POR_TRASLADO (length: 255)
        public string Nodo { get; set; } // NODO (length: 15)
        public string TelefonoCelular { get; set; } // TELEFONO_CELULAR (length: 50)
        public string TelefonoFijo { get; set; } // TELEFONO_FIJO (length: 50)
        public string CorreoElectronico { get; set; } // CORREO_ELECTRONICO (length: 255)
        public string Observacion { get; set; } // OBSERVACION (length: 1073741823)
    }

}
// </auto-generated>
