// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // TBL_USABILIDAD_ACTIVACION_CONVENIO
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class UsabilidadActivacionConvenio
    {
        public int Id { get; set; } // ID (Primary key)
        public System.DateTime? FechaRevision { get; set; } // FECHA_REVISION
        public int? IdUsuarioRevision { get; set; } // ID_USUARIO_REVISION
        public string NombreUsarioRevison { get; set; } // NOMBRE_USARIO_REVISON (length: 100)
        public int? CuentaRevisoTabla { get; set; } // CUENTA_REVISO_TABLA
    }

}
// </auto-generated>
