// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // USUARIOS_GENERICOS
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class UsuariosGenerico
    {
        public decimal IdUsuario { get; set; } // ID_USUARIO
        public decimal Cedula { get; set; } // CEDULA (Primary key)
        public string Nombre { get; set; } // NOMBRE (length: 100)
        public string UsuarioRr { get; set; } // USUARIO_RR (length: 30)
        public string UsuarioAgendamiento { get; set; } // USUARIO_AGENDAMIENTO (length: 30)
        public string Contrasena { get; set; } // CONTRASENA (length: 100)
        public int? IdRol { get; set; } // ID_ROL
        public decimal? IdNombreLinea { get; set; } // ID_NOMBRE_LINEA
        public int? Acceso1 { get; set; } // ACCESO_1
        public int? Acceso2 { get; set; } // ACCESO_2
        public int? Acceso3 { get; set; } // ACCESO_3
        public int? Acceso4 { get; set; } // ACCESO_4
        public int? Acceso5 { get; set; } // ACCESO_5
        public int? Acceso6 { get; set; } // ACCESO_6
        public int? Acceso7 { get; set; } // ACCESO_7
        public int? Acceso8 { get; set; } // ACCESO_8
        public int? Acceso9 { get; set; } // ACCESO_9
        public int? Acceso10 { get; set; } // ACCESO_10
        public int? Acceso11 { get; set; } // ACCESO_11
        public int? Acceso12 { get; set; } // ACCESO_12
        public int? Acceso13 { get; set; } // ACCESO_13
        public int? Acceso14 { get; set; } // ACCESO_14
        public int? Acceso15 { get; set; } // ACCESO_15
        public int? Acceso16 { get; set; } // ACCESO_16
        public int? Acceso17 { get; set; } // ACCESO_17
        public int? Acceso18 { get; set; } // ACCESO_18
        public int? Acceso19 { get; set; } // ACCESO_19
        public int? Acceso20 { get; set; } // ACCESO_20
        public int? Acceso21 { get; set; } // ACCESO_21
        public int? Acceso22 { get; set; } // ACCESO_22
        public int? Acceso23 { get; set; } // ACCESO_23
        public int? Acceso24 { get; set; } // ACCESO_24
        public int? Acceso25 { get; set; } // ACCESO_25
        public int? Acceso26 { get; set; } // ACCESO_26
        public int? Acceso27 { get; set; } // ACCESO_27
        public int? Acceso28 { get; set; } // ACCESO_28
        public int? Acceso29 { get; set; } // ACCESO_29
        public int? Acceso30 { get; set; } // ACCESO_30
    }

}
// </auto-generated>
