// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // TBL_USUARIOS_NOTIFICADOS
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class UsuariosNotificado
    {
        public decimal IdVisto { get; set; } // ID_VISTO (Primary key)
        public decimal? IdNotificado { get; set; } // ID_NOTIFICADO
        public string Usuario { get; set; } // USUARIO (length: 30)
        public System.DateTime? FechaVisto { get; set; } // FECHA_VISTO
        public string NombreImagenVista { get; set; } // NOMBRE_IMAGEN_VISTA (length: 100)
        public string LinkDireccionamiento { get; set; } // LINK_DIRECCIONAMIENTO (length: 500)
        public string DescripcionImagenVista { get; set; } // DESCRIPCION_IMAGEN_VISTA (length: 500)
        public string AliadoUsuario { get; set; } // ALIADO_USUARIO (length: 100)
        public string PerfilUsuario { get; set; } // PERFIL_USUARIO (length: 100)
        public string NombreLineaUsuario { get; set; } // NOMBRE_LINEA_USUARIO (length: 100)
    }

}
// </auto-generated>
