// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // USUARIOS_GENERICOS
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class UsuariosGenericoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<UsuariosGenerico>
    {
        public UsuariosGenericoConfiguration()
            : this("dbo")
        {
        }

        public UsuariosGenericoConfiguration(string schema)
        {
            ToTable("USUARIOS_GENERICOS", schema);
            HasKey(x => x.Cedula);

            Property(x => x.IdUsuario).HasColumnName(@"ID_USUARIO").IsRequired().HasColumnType("numeric").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Cedula).HasColumnName(@"CEDULA").IsRequired().HasColumnType("numeric").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Nombre).HasColumnName(@"NOMBRE").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(100);
            Property(x => x.UsuarioRr).HasColumnName(@"USUARIO_RR").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(30);
            Property(x => x.UsuarioAgendamiento).HasColumnName(@"USUARIO_AGENDAMIENTO").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(30);
            Property(x => x.Contrasena).HasColumnName(@"CONTRASENA").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(100);
            Property(x => x.IdRol).HasColumnName(@"ID_ROL").IsOptional().HasColumnType("int");
            Property(x => x.IdNombreLinea).HasColumnName(@"ID_NOMBRE_LINEA").IsOptional().HasColumnType("numeric");
            Property(x => x.Acceso1).HasColumnName(@"ACCESO_1").IsOptional().HasColumnType("int");
            Property(x => x.Acceso2).HasColumnName(@"ACCESO_2").IsOptional().HasColumnType("int");
            Property(x => x.Acceso3).HasColumnName(@"ACCESO_3").IsOptional().HasColumnType("int");
            Property(x => x.Acceso4).HasColumnName(@"ACCESO_4").IsOptional().HasColumnType("int");
            Property(x => x.Acceso5).HasColumnName(@"ACCESO_5").IsOptional().HasColumnType("int");
            Property(x => x.Acceso6).HasColumnName(@"ACCESO_6").IsOptional().HasColumnType("int");
            Property(x => x.Acceso7).HasColumnName(@"ACCESO_7").IsOptional().HasColumnType("int");
            Property(x => x.Acceso8).HasColumnName(@"ACCESO_8").IsOptional().HasColumnType("int");
            Property(x => x.Acceso9).HasColumnName(@"ACCESO_9").IsOptional().HasColumnType("int");
            Property(x => x.Acceso10).HasColumnName(@"ACCESO_10").IsOptional().HasColumnType("int");
            Property(x => x.Acceso11).HasColumnName(@"ACCESO_11").IsOptional().HasColumnType("int");
            Property(x => x.Acceso12).HasColumnName(@"ACCESO_12").IsOptional().HasColumnType("int");
            Property(x => x.Acceso13).HasColumnName(@"ACCESO_13").IsOptional().HasColumnType("int");
            Property(x => x.Acceso14).HasColumnName(@"ACCESO_14").IsOptional().HasColumnType("int");
            Property(x => x.Acceso15).HasColumnName(@"ACCESO_15").IsOptional().HasColumnType("int");
            Property(x => x.Acceso16).HasColumnName(@"ACCESO_16").IsOptional().HasColumnType("int");
            Property(x => x.Acceso17).HasColumnName(@"ACCESO_17").IsOptional().HasColumnType("int");
            Property(x => x.Acceso18).HasColumnName(@"ACCESO_18").IsOptional().HasColumnType("int");
            Property(x => x.Acceso19).HasColumnName(@"ACCESO_19").IsOptional().HasColumnType("int");
            Property(x => x.Acceso20).HasColumnName(@"ACCESO_20").IsOptional().HasColumnType("int");
            Property(x => x.Acceso21).HasColumnName(@"ACCESO_21").IsOptional().HasColumnType("int");
            Property(x => x.Acceso22).HasColumnName(@"ACCESO_22").IsOptional().HasColumnType("int");
            Property(x => x.Acceso23).HasColumnName(@"ACCESO_23").IsOptional().HasColumnType("int");
            Property(x => x.Acceso24).HasColumnName(@"ACCESO_24").IsOptional().HasColumnType("int");
            Property(x => x.Acceso25).HasColumnName(@"ACCESO_25").IsOptional().HasColumnType("int");
            Property(x => x.Acceso26).HasColumnName(@"ACCESO_26").IsOptional().HasColumnType("int");
            Property(x => x.Acceso27).HasColumnName(@"ACCESO_27").IsOptional().HasColumnType("int");
            Property(x => x.Acceso28).HasColumnName(@"ACCESO_28").IsOptional().HasColumnType("int");
            Property(x => x.Acceso29).HasColumnName(@"ACCESO_29").IsOptional().HasColumnType("int");
            Property(x => x.Acceso30).HasColumnName(@"ACCESO_30").IsOptional().HasColumnType("int");
        }
    }

}
// </auto-generated>
