// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // TBL_USUARIOS_X_PREGUNTAS_DESB
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class UsuariosXPreguntasDesb
    {
        public int Id { get; set; } // ID
        public int IdPregunta { get; set; } // ID_PREGUNTA
        public int IdUsuario { get; set; } // ID_USUARIO
        public string Respuesta { get; set; } // RESPUESTA (length: 200)

        // Foreign keys
        public virtual PreguntasDesbloqueo PreguntasDesbloqueo { get; set; } // FK__TBL_USUAR__ID_PR__50FB042B
        public virtual Usuario Usuario { get; set; } // FK__TBL_USUAR__ID_US__51EF2864
    }

}
// </auto-generated>
