// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // V_ACTUALIZAR_SEMAFORO
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class VActualizarSemaforo
    {
        public decimal? CuentaCliente { get; set; } // CUENTA_CLIENTE
        public decimal IdIngreso { get; set; } // ID_INGRESO
        public decimal? IdNota { get; set; } // ID_NOTA
        public System.DateTime? Fecha { get; set; } // FECHA
        public int? Dias { get; set; } // DIAS
        public int? DiasT { get; set; } // DIAS_T
    }

}
// </auto-generated>
