// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Telmexla.Servicios.DIME.Helpers.ReverseEngineer
{

    // V_ACTUALIZAR_SEMAFORO
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class VActualizarSemaforoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<VActualizarSemaforo>
    {
        public VActualizarSemaforoConfiguration()
            : this("dbo")
        {
        }

        public VActualizarSemaforoConfiguration(string schema)
        {
            ToTable("V_ACTUALIZAR_SEMAFORO", schema);
            HasKey(x => x.IdIngreso);

            Property(x => x.CuentaCliente).HasColumnName(@"CUENTA_CLIENTE").IsOptional().HasColumnType("numeric");
            Property(x => x.IdIngreso).HasColumnName(@"ID_INGRESO").IsRequired().HasColumnType("numeric");
            Property(x => x.IdNota).HasColumnName(@"ID_NOTA").IsOptional().HasColumnType("numeric");
            Property(x => x.Fecha).HasColumnName(@"FECHA").IsOptional().HasColumnType("datetime");
            Property(x => x.Dias).HasColumnName(@"DIAS").IsOptional().HasColumnType("int");
            Property(x => x.DiasT).HasColumnName(@"DIAS_T").IsOptional().HasColumnType("int");
        }
    }

}
// </auto-generated>
