// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using Telmexla.Servicios.DIME.Entity;
namespace Telmexla.Servicios.DIME.Data.Configuration
{

    // TMP_PQR_MAESTRO_COD_CIERRE
    public class PqrMaestroCodCierreConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<PqrMaestroCodCierre>
    {
        public PqrMaestroCodCierreConfiguration()
            : this("dbo")
        {
        }

        public PqrMaestroCodCierreConfiguration(string schema)
        {
            ToTable("TMP_PQR_MAESTRO_COD_CIERRE", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"ID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Razon).HasColumnName(@"RAZON").IsOptional().HasColumnType("nvarchar").HasMaxLength(255);
            Property(x => x.SubRazon).HasColumnName(@"SUB_RAZON").IsOptional().HasColumnType("nvarchar").HasMaxLength(255);
            Property(x => x.CodigoRr).HasColumnName(@"CODIGO_RR").IsOptional().HasColumnType("float");
            Property(x => x.CodigoCierre).HasColumnName(@"CODIGO_CIERRE").IsOptional().HasColumnType("nvarchar").HasMaxLength(255);
            Property(x => x.Clase).HasColumnName(@"CLASE").IsOptional().HasColumnType("nvarchar").HasMaxLength(255);
            Property(x => x.ReporteSic).HasColumnName(@"REPORTE_SIC").IsOptional().HasColumnType("nvarchar").HasMaxLength(255);
            Property(x => x.Producto).HasColumnName(@"PRODUCTO").IsOptional().HasColumnType("nvarchar").HasMaxLength(255);
        }
    }

}
// </auto-generated>
