// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning
using Telmexla.Servicios.DIME.Entity;

namespace Telmexla.Servicios.DIME.Data.Configuration
{

    // TBL_RECHAZOS
    public class RechazoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Rechazo>
    {
        public RechazoConfiguration()
            : this("dbo")
        {
        }

        public RechazoConfiguration(string schema)
        {
            ToTable("TBL_RECHAZOS", schema);
            HasKey(x => x.IdRechazo);

            Property(x => x.IdRechazo).HasColumnName(@"ID_RECHAZO").IsRequired().HasColumnType("numeric").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.IdIngreso).HasColumnName(@"ID_INGRESO").IsOptional().HasColumnType("numeric");
            Property(x => x.FechaCreacionCaso).HasColumnName(@"FECHA_CREACION_CASO").IsOptional().HasColumnType("date");
            Property(x => x.HoraCreacionCaso).HasColumnName(@"HORA_CREACION_CASO").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.UsuarioCreacionCaso).HasColumnName(@"USUARIO_CREACION_CASO").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.NotasRechazo).HasColumnName(@"NOTAS_RECHAZO").IsOptional().HasColumnType("nvarchar").HasMaxLength(500);
            Property(x => x.UsuarioRechaza).HasColumnName(@"USUARIO_RECHAZA").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.FechaRechazo).HasColumnName(@"FECHA_RECHAZO").IsOptional().HasColumnType("date");
            Property(x => x.HoraRechazo).HasColumnName(@"HORA_RECHAZO").IsOptional().HasColumnType("datetime");
        }
    }

}
// </auto-generated>
